language: node_js
sudo: false
node_js:
  - "iojs"
  - "0.12"
  - "0.11"
  - "4"
  - "5"
services:
  - mysql
before_script:
  - mysql -e "create database IF NOT EXISTS knex;" -uroot
  - mysql -Dknex -uroot < test/fixtures/travis.sql
script:
  - npm run instrument
  - npm test
after_success:
  - cat lcov.info | ./node_modules/.bin/codecov
