language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
script:
  - npm run instrument
  - npm test
after_success:
  - cat lcov.info | ./node_modules/.bin/codecov
notifications:
  email: false
